CREATE TABLE public.app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    iin      varchar(50)                             NOT NULL,
    name     varchar(50)                             NOT NULL,
    phone    varchar(50)                             NOT NULL,
    email    varchar(50)                             NOT NULL,
    password varchar(50)                             NOT NULL,
    isActive BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);
